
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ${PROMETHEUS_HOST}
    hostname: ${PROMETHEUS_NAME}
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_INTERNAL_PORT}
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    networks:
      - proxy-net

  loki:
    image: grafana/loki:2.9.6
    container_name: ${LOKI_HOST}
    hostname: ${LOKI_NAME}
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - ${LOKI_INTERNAL_PORT}
    volumes:
      - ./loki/local-config.yml:/etc/loki/local-config.yml:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy-net

  grafana:
    image: grafana/grafana:latest
    container_name: ${GRAFANA_HOST}
    hostname: ${GRAFANA_NAME}
    restart: unless-stopped
    ports:
      - ${GRAFANA_INTERNAL_PORT}
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_SECURITY_ADMIN_PASSWORD}
      - PROMETHEUS_NAME=${PROMETHEUS_NAME}
      - PROMETHEUS_INTERNAL_PORT=${PROMETHEUS_INTERNAL_PORT}
      - LOKI_NAME=${LOKI_NAME}
      - LOKI_INTERNAL_PORT=${LOKI_INTERNAL_PORT}

    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/data:/var/lib/grafana
    networks:
      - proxy-net

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: ${NODE_EXPORTER_NAME}
  #   restart: unless-stopped
  #   command:
  #     - '--path.sysfs=/host/sys'
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/host/root'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
  #   expose:
  #     - "${NODE_EXPORTER_PORT}"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/host/root:ro
  #   networks:
  #     - proxy-net

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:v0.47.2
  #   container_name: ${CADVISOR_NAME}
  #   restart: unless-stopped
  #   privileged: true
  #   expose:
  #     - "${CADVISOR_PORT}"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #   networks:
  #     - proxy-net

  edge:
    image: nginx:alpine
    container_name: ${EDGE_HOST}
    hostname: ${EDGE_NAME}
    restart: unless-stopped

    volumes:
      - ./edge/nginx/conf.d:/etc/nginx/conf.d
      - ./edge/nginx/templates:/etc/nginx/templates:ro

    environment:
      VIRTUAL_HOST: ${GRAFANA_HOST},${PROMETHEUS_HOST},${LOKI_HOST}
      LETSENCRYPT_HOST: ${GRAFANA_HOST},${PROMETHEUS_HOST},${LOKI_HOST}
      LETSENCRYPT_EMAIL: ${EMAIL}
      GRAFANA_NAME: ${GRAFANA_NAME}
      GRAFANA_HOST: ${GRAFANA_HOST}
      GRAFANA_INTERNAL_PORT: ${GRAFANA_INTERNAL_PORT}
      PROMETHEUS_NAME: ${PROMETHEUS_NAME}
      PROMETHEUS_HOST: ${PROMETHEUS_HOST}
      PROMETHEUS_INTERNAL_PORT: ${PROMETHEUS_INTERNAL_PORT}
      LOKI_NAME: ${LOKI_NAME}
      LOKI_HOST: ${LOKI_HOST}
      LOKI_INTERNAL_PORT: ${LOKI_INTERNAL_PORT}

    depends_on:
      - grafana
      - prometheus
      - loki

    expose:
      - ${EDGE_PORT}
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
    name: proxy-net
